[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"

[project]
name = "get-sed-and-classify"
version = "0.4.1"
requires-python = ">=3.10"

[tool.setuptools.packages.find]
where = ["src"]
